# Generated by Django 2.1 on 2019-01-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0004_auto_20190114_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
