# Generated by Django 2.1 on 2019-01-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0005_auto_20190114_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
