# Generated by Django 2.1 on 2019-01-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0007_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
