# Generated by Django 2.1 on 2019-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0009_auto_20190119_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
