# Generated by Django 2.1 on 2019-01-20 19:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0012_auto_20190120_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account_no',
        ),
    ]
