# Generated by Django 2.1 on 2019-01-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190123_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_no',
        ),
    ]
